/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "vaults-dev",
            "region": "us-west-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-west-2:a3b54019-cc6f-4e8f-b6df-a160f651771e",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_hua9ftbRd",
    "aws_user_pools_web_client_id": "2ionjfmg8kqasc2l6q9h9eoa8i",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "jmvApi2",
            "endpoint": "https://qvmou2l6zf.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
